### ISSUE TITLE
Standard Error when adding Array Control

### ISSUE THREAD

**Issue by hin101** [jonspalmer/view_component-storybook#114]
I am getting a `StandardError: Validation failed: Param can't be blank`, when I run the rake task: `view_component_storybook:write_stories_json`.

Here is the story block I am using:

```
story :heading_with_counter do
      title do
        'Page Title'
      end
      counter(collection: array([1,2,3]), collection_type: :number)
    end
 ```
 
 I suspect it's `array([1,2,3])` which causes the issue, as if I take it out it works fine.

**Comment by jonspalmer** [comment]
It would be great to get a failing test case in a PR to investigate this against. Do you think you could put that together?

**Comment by jonspalmer** [comment]
With V1 APi this issue is expected to be obsolete. Please reopen with a failing test case if it's not.
