### ISSUE TITLE
Cannot use slots with the same name as a Control method

### ISSUE THREAD

**Issue by TastyPi** [jonspalmer/view_component-storybook#127]
I have a control with a slot named `select` (because it created a `<select>` element), but that means I can't use it easily within a story as it just calls the `select` control method instead.

It would be nice if there was a way to access slots in a scoped way that does not conflict with controls, e.g. `slots.select(...)`.

**Comment by TastyPi** [comment]
My workaround for this is to call `undef :select` just before setting up the slot, but obviously that's not ideal.

**Comment by jonspalmer** [comment]
Circling back to this conversation I'm curious if you have thoughts on the discussion in #150

**Comment by jonspalmer** [comment]
fixed in v1.0.0
