### ISSUE TITLE
Adding framework field in the main.js file

### ISSUE THREAD

**Issue by Kjaer** [jonspalmer/view_component-storybook#133]
Hello there. We're using this storybook setup for developing our own components. Currently I upgraded my storybook to the latest (6.5.5) and received an error-like warning:

```sh
 npx sb@latest automigrate
🔎 checking possible migrations..
❌ Unable to determine storybook version, skipping mainjsFramework fix.
🤔 Are you running automigrate from your project directory?

✅ migration check successfully ran
```

I dug a little and find out storybook started to add `framework` field on the main.js file for the newer versions:
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#mainjs-framework-field

I tried to use `@storybook/html` for the framework. It seems most close for that option but it failed.
<img width="926" alt="Screenshot 2022-05-27 at 16 28 13" src="https://user-images.githubusercontent.com/1381484/170708749-299bebe8-9fc7-44e0-b243-e94015ded049.png">

So what do you think for this new field?

P.S. here are the supported framework list from storybook:
https://github.com/storybookjs/storybook/blob/next/lib/postinstall/src/frameworks.ts#L7-L21

**Comment by jonspalmer** [comment]
I need to do some digging on the latest changes in Storybook versions. I suspect this is an easy fix but the changes might be on the storybook side.

**Comment by jonspalmer** [comment]
I just updated the example repo to use Storybook 6.5.5 and it seems to work fine. Can you check that out so we can figure out what the difference is with your config? https://github.com/jonspalmer/view_component_storybook_example

**Comment by jonspalmer** [comment]
Closing this as stale
