### ISSUE TITLE
rake view_component_storybook:write_stories_json not found

### ISSUE THREAD

**Issue by lannn** [jonspalmer/view_component-storybook#135]
I've followed this document: https://jonspalmer.github.io/view_component_storybook/guide/getting-started.html
and run
```
rake view_component_storybook:write_stories_json
```
but rake is not found
```
rake aborted!
Don't know how to build task 'view_component_storybook:write_stories_json' (See the list of available tasks with `rake --tasks`)
```
I've tested on both rails 6 and rails 7

**Comment by jonspalmer** [comment]
have you installed the gems with bundler?

**Comment by deweydell** [comment]
I'm having the same issue and I have installed both gems with bundler 🤔

**Comment by AlainPilon** [comment]
+1 Same issue here.

**Comment by jonspalmer** [comment]
What version are you using? This works in the example app

**Comment by zthornto** [comment]
Specifying a require within the Gemfile ended up being the fix on my end for this same issue:
`gem 'view_component_storybook', require: 'view_component/storybook'`

**Comment by jonspalmer** [comment]
Can you please retest this against v1. Many of the internals have changed

**Comment by EricRoos** [comment]
Still having issues for me unfortunately :/

**Comment by navrocky** [comment]
Just use:
```
gem "view_component-storybook"
```
instead of:
```
gem 'view_component_storybook', require: 'view_component/storybook'
```
Look carefully at the package name.

**Comment by jonspalmer** [comment]
Closing with @navrocky suggestion that this was fixed in v1 admittedly with the confusing but necessary change in package name. Please repoen with reproduce steps if thisis a lingering issue.
