### ISSUE TITLE
Non-Conventional Gem Name

### ISSUE THREAD

**Issue by blowmage** [jonspalmer/view_component-storybook#152]
The installation instructions direct users to add a require to `config/application.rb`. This would be unnecessary if this gem followed the [RubyGems naming conventions](https://guides.rubygems.org/name-your-gem/). Bundler would auto-require `view_component/storybook` if the gem was named `view_component-storybook` instead of `view_component_storybook`.

I would like to see this gem renamed to `view_component-storybook` and installation instructions changed to direct users to use `bundle add view_component-storybook --group development`. I am happy to open a PR for this change if desired.

**Comment by jonspalmer** [comment]
fixed in v1.0.0

**Comment by blowmage** [comment]
ᕕ( ᐛ )ᕗ

**Comment by jonspalmer** [comment]
RubyGems won't let me push a gem with the new name because it's too similar to the old one. They don't seem to have a rename feature (·•᷄∩•᷅ ). Reached out to their support to see if there is a fix.

**Comment by blowmage** [comment]
Has RubyGems support responded to you yet? I've seen this "too similar" behavior before, but RubyGems has always allowed this when asked.
