### ISSUE TITLE
All documentation refers to the 1.0.0 API, which is not available through normal installation (Unable to load story '*' storybook)

### ISSUE THREAD

**Issue by decaruju** [jonspalmer/view_component-storybook#155]
You should maybe specify in the readme that the gem should be installed using the git url, or link the documentation to the 0.12.0 version ?

The documentation https://jonspalmer.github.io/view_component-storybook/ doesn't show a version, but one would assume it is for the most up to date available version, not the unreleased version with a different API.

The gem repository https://rubygems.org/gems/view_component_storybook only lists versions up to 0.12.0.

I think some clarity is needed to avoid headaches from the users of the gem.

The error which is displayed in the browser console is `unable to load story '*' storybook` when trying to use the documented API (for version 1.0.0) with the latest available version (0.12.0).

The documentation for version 0.12.0 can be found here https://github.com/jonspalmer/view_component-storybook/blob/add8d273d218c788c238580f1ac00e06d210313e/docs/guide/getting-started.md .

**Comment by jonspalmer** [comment]
There was a problem with publishing the v1.0.0 with the updated name. Now fixed. Please confirm this is fixed for you and we can close this out.

**Comment by decaruju** [comment]
Yes it works now!

Thanks !

**Comment by unikitty37** [comment]
The CHANGELOG.md still seems to think that 0.12.1 is the current version, which is not ideal when there are breaking changes. Has it moved somewhere else? (It took me long enough to notice that there was one, but it was in docs/ rather than the root :)
