### ISSUE TITLE
Slots documentation has not been updated for v1 API

### ISSUE THREAD

**Issue by unikitty37** [jonspalmer/view_component-storybook#165]
2781fb4afefb137df2ed454bf074e321fce2087c updated the documentation for the v1 API, but the only changes made to the slots guide was to change the navigation order. As a consequence, the examples in the documentation aren't usable with v1.0.

Please could this be updated? I've managed to work something out from spec/dummy/test/components/stories/slots_stories.rb, but I don't feel confident enough to update the documentation so far :)

**Comment by jonspalmer** [comment]
Updated the docs. Thanks for the find
