### ISSUE TITLE
Rendering multiple view components in a story

### ISSUE THREAD

**Issue by KonnorRogers** [jonspalmer/view_component-storybook#70]
Im curious if theres a way to render multiple components in a single story. 

`Component.with_collection(posts)`

is what im using in my app, but I cant find any prior art on how to render multiple components like with a collection. I tried calling `constructor` twice, but it only takes the last instance.

I know i could swap to just passing in a collection, but I was curious if there was a nicer way to do this.

**Comment by jonspalmer** [comment]
We don't have support for that at the moment. We are mirroring the Preview feature in ViewComponent (and in turn Rails Mailer previews) with is very much single component focused. 

If we did add it its not clear how we'd format the list in HTML etc and it would also be harder to figure out how to pass control values to them. Of course if you have a higher level component that renders a list of components (perhaps as a `render_many` slot) then we'd support that well.

**Comment by jonspalmer** [comment]
Circling back to this conversation I'm curious if you have thoughts on the discussion in #150

**Comment by jonspalmer** [comment]
fixed in v1.0.0

Storeis are not just ViewComponent Previews. Using custom templates you can now render multiple Components.
